option(ASTRA_WARNINGS_AS_ERRORS "将项目编译告警作为错误" ON)
set(ASTRA_SANITIZER "none" CACHE STRING "none/address/thread")
set_property(CACHE ASTRA_SANITIZER PROPERTY STRINGS none address thread)

add_library(astra_options INTERFACE)
target_compile_features(astra_options INTERFACE cxx_std_20)
set(CMAKE_CXX_EXTENSIONS OFF)
target_compile_definitions(astra_options INTERFACE JSON_NOEXCEPTION=1)
if(MSVC)
  target_compile_options(astra_options INTERFACE /W4 /permissive-)
  if(ASTRA_WARNINGS_AS_ERRORS)
    target_compile_options(astra_options INTERFACE /WX)
  endif()
else()
  target_compile_options(astra_options INTERFACE -Wall -Wextra -Wpedantic -fno-exceptions)
  if(ASTRA_WARNINGS_AS_ERRORS)
    target_compile_options(astra_options INTERFACE -Werror)
  endif()
endif()

if(NOT ASTRA_SANITIZER STREQUAL "none")
  if(MSVC OR NOT CMAKE_SYSTEM_NAME MATCHES "^(Linux|Darwin)$")
    message(FATAL_ERROR "当前工具链未配置所选 sanitizer")
  endif()
  if(ASTRA_SANITIZER STREQUAL "address")
    set(astra_sanitizer_flags -fsanitize=address,undefined -fno-omit-frame-pointer)
  elseif(ASTRA_SANITIZER STREQUAL "thread")
    set(astra_sanitizer_flags -fsanitize=thread -fno-omit-frame-pointer)
  else()
    message(FATAL_ERROR "未知 ASTRA_SANITIZER=${ASTRA_SANITIZER}")
  endif()
  target_compile_options(astra_options INTERFACE ${astra_sanitizer_flags})
  target_link_options(astra_options INTERFACE ${astra_sanitizer_flags})
endif()
